### PR TITLE
Add strategy option

### PR DESCRIPTION
**Pull request by caiofbpa**
For very large test suites, splitting only by method/function name isn't a good idea because the test runners end up executing unnecessary `setUp`s and `tearDown`s.

Most test suites that have very slow tests, e.g. selenium, group them in the same package or directory, so it would be very interesting to be able to split tests based on directory also, in a way that each node gets one of those tests to run, splitting more evenly the test load (and time) across nodes.

This PR adds the `--parallel-strategy` option to let users customize how `nose-parallel` splits tests across nodes.

The default strategy is still to split by method/function name, so this should be retro compatible.

### CODE REVIEW

**Comment by dlanger** [comment]
Thank you for both this and #15 - I'll take a look over the weekend. 

Does using multiple strategies at different "levels" open the possibility that tests might get missed? For example, if someone uses `--parallel-strategy=CLASS --parallel-strategy=FILE`, `wantFile` is `None` (meaning the current node should run the file) and `wantClass` is `False` (meaning the current node should not run the file), where do the tests in that class get run?

**Comment by caiofbpa** [comment]
@dlanger I'm testing this out as we speak, but yes this might be possible. Perhaps we should warn users on the documentation, or we could try to "protect" them by forbidding some strategy combinations... What do you think?

**Comment by dlanger** [comment]
My first thought would be to only allow one strategy at once (while having some special-casing to maintain backwards compatibility). Would that work with the use case that caused you to write this?

**Comment by caiofbpa** [comment]
@dlanger after some experimentation, the strategy that has performed best to me is the MODULE strategy. I haven't tried all combinations, but the ones that I tried left out some tests. So I'm in favor of allowing only one strategy at a time. Probably METHOD,FUNCTION should be the only combination allowed, what do you think?

**Comment by dlanger** [comment]
I like it. What about only allowing one, and then having `DEFAULT` (or some other single term) represent existing behavior? Having only one option with a comma sounds confusing.

**Comment by caiofbpa** [comment]
@dlanger done. I'll test this new version against my codebase here.

**Review by dlanger — APPROVED** [review]

**Comment by caiofbpa** [comment]
@dlanger conflict resolved

**Review by dlanger — APPROVED** [review]

**Comment by dlanger** [comment]
Thanks for your work on this, @caiofbpa! I'll cut a new release to PyPI later today.

**Comment by dlanger** [comment]
@caiofbpa Version `0.4.0` out on PyPI

**Pull request merged**
